### ISSUE TITLE
Building for PSP failes upon linking libSDL_mixed

### ISSUE THREAD

**Issue by Phyksar** [dbeef/spelunky-psp#148]
I'm trying to use`pspdev/pspdev:latest` docker image to build the project, this includes the psp toolchain required in the [building instructions](https://github.com/dbeef/spelunky-psp/blob/master/readme/Building.md). The image, along with the psp toolchain is based upon alpine linux, however I get linking errors when calling `./scripts/build-psp.sh`.
```
[100%] Linking CXX executable Spelunky_PSP
/usr/local/pspdev/lib/gcc/psp/13.2.0/../../../../psp/bin/ld: /usr/local/pspdev/psp/lib/libSDL_mixer.a(music_cmd.o): in function `MusicCMD_Start':
(.text+0x23c): undefined reference to `sigprocmask'
/usr/local/pspdev/lib/gcc/psp/13.2.0/../../../../psp/bin/ld: /usr/local/pspdev/psp/lib/libSDL_mixer.a(music_cmd.o): in function `MusicCMD_Stop':
(.text+0x2e0): undefined reference to `waitpid'
/usr/local/pspdev/lib/gcc/psp/13.2.0/../../../../psp/bin/ld: /usr/local/pspdev/psp/lib/libSDL_mixer.a(music_cmd.o): in function `MusicCMD_Active':
(.text+0x370): undefined reference to `waitpid'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/Spelunky_PSP.dir/build.make:121: Spelunky_PSP] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:501: CMakeFiles/Spelunky_PSP.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```
It looks like alpine doesn't define `sigprocmask`, `waitpid` functions used in `libSDL_mixer`. What can I do with this and how this is supposed to be built? I have no idea, since switching to any other linux distributive would be a very time-consuming task as it requires to recursively modify all the images used in the pspdev build.

**Comment by dbeef** [comment]
I did replicate the error you're experiencing. Took a few steps but now I got it building with the most recent toolchain image. It involved:

* Updating glm to more recent version (as gcc bundled within the new toolchain image has been updated, it resulted in some compilation errors in glm that's included within the repo)
* Removing linking to libvorbisidec + Replacing the `Audio` CMake target implementation with the dummy one (temporary workaround until I figure out what to do with symbols missing in libSDL_mixer)

I have some appointments now, but I will push what I have soon. The problems come from the fact that I have not built a PSP artifact for some time and when I do, I have a local toolchain on my computer so I'm not affected by the toolchain changes such as gcc upgrade or changes within shipped toolchain libraries. Sorry for inconvenience and at the same time - thanks for reporting the issue.

**Comment by dbeef** [comment]
You're welcome, I spend much less time developing SpelunkyPSP nowadays but I'm always happy to help. 
I pushed my changes to: https://github.com/dbeef/spelunky-psp/pull/149 - It includes updating glm, disabling the audio module (temporarily hides the problem with libSDL_mixer - later can be solved by just switching to libSDL2_mixer as it does not reference those missing symbols), and also an attempt to fix a warning that comes from `psp-fixup-imports`, that is "_Warning: could not fixup imports, stubs out of order_". 

It builds, the resulting EBOOT.PBP file opens in an emulator (I'm using PPSSPP) and I can play without any problems, however when I try running it on a real PSP I get "_The game could not be started. (8002013C)_" error message. 

I think the error is related to this warning from `psp-fixup-imports`. I will investigate this more in the following days. Cheers.

**Comment by dbeef** [comment]
An update: 

- I resolved the psp-fixup-imports warning - just like the message suggested I forced linking PSP SDK libraries as last by aggregating all PSP-SDK libs into an extra interface target in CMake (for some reason only this guaranteed they will really be last in the list) - The warning is gone, however it didn't fix the crash on PSP, which turns out to be...
- ...Most probably the change of default firmware version in the PSP toolchain which I tracked to a group of commits from March this year: https://github.com/pspdev/pspsdk/commit/2b4e9493abf17866521979a609b8b8435998a667 https://github.com/pspdev/pspsdk/commit/b9cbe7f1c32da3884af275a8ebc02db053c433e4
- With the change of default supported firmware from `PSP_FW_VERSION=150` to `PSP_FW_VERSION=600` now it makes sense that the build worked on an emulator, but failed on my PSP (firmware <600) with error code 8002013C 
- This means that if you have more recent firmware on your PSP then the build from `adjusting-to-updated-pspsdk` branch will run just fine (yet without sound)
- Re-enabling sound is the last thing to be solved. It could be that moving to SDL2 will be required (which for some reason is challenging to make it work with `glad`, unlike SDL1, which is the reason I sticked to the latter)
- Well, this and thinking what to do with the firmware issue - I don't want to drop support for older firmware if it can be avoided, yet it will probably not be enough to build SpelunkyPSP with `PSP_FW_VERSION=150`, but all libraries included with the toolchain (such as SDL) with `PSP_FW_VERSION=150`. To be honest, I might just go with `600` for simple convenience of not branching off the mainstream PSP toolchain image / delivering my own prebuilt dependencies for `150`.

I will post the next update (hopefully - with the audio module re-enabled) in a few days. Cheers.

**Comment by dbeef** [comment]
Got it working :D Building on `pspdev/pspdev:latest`, running on PSP-1000 6.60 CFW.

![IMG_4560_small](https://github.com/dbeef/spelunky-psp/assets/13459304/8ae17b52-4095-49b2-b613-ace185ed9c6c)

On top of the previous changes:

* Updated firmware on my PSP (as a result of the new default version in the PSP toolchain: `PSP_FW_VERSION=600`)
* Switched both video / GL context creation on PSP to SDL2
* Switched audio implementation on PSP to use SDL2_mixer (works!)
* As anticipated, glad can't retrieve GL function pointers using SDL2, using `SDL2/SDL_opengl.h` header as a workaround.

I will push the fixes tomorrow, hopefully I come up with something to still use glad. 

Unwelcome side effect - switching from SDL1 to SDL2 results with significantly bigger artifact (EBOOT.PBP) - an increase from 15.8 MB to 17.8 MB

**Comment by dbeef** [comment]
I just merged the relevant changes: https://github.com/dbeef/spelunky-psp/pull/149

You can now build the project with `pspdev/pspdev:latest`.
Example usage:

```sh
git clone git@github.com:dbeef/spelunky-psp.git
cd spelunky-psp
sudo docker run --rm -it -v $(pwd):/root pspdev/pspdev:latest /bin/bash
# Inside the container:
cd
./scripts/config-psp.sh
./scripts/build-psp.sh
```

Thank you for reporting the issue.
